* project-hercules.el
This is a convenient helper for defining per-project transient keymaps using [[https://gitlab.com/jjzmajic/hercules.el][hercules.el]].
** Configuration
The following is an example configuration with =use-package=:

#+begin_src emacs-lisp
  (use-package project-hercules
    :general
    ("M-SPC" project-hercules-dispatch)
    :config
    ;; Load preconfigured maps
    (require 'project-hercules-config))
#+end_src

Bind a key to =project-hercules-dispatch= command.

The default keymap is constructed according to files existing in the project directory.
This is defined in =project-hercules-composed-maps= custom variable.
See =project-hercules-config.el= for an example.
** Usage
Use =project-hercules-make-map= to define per-project keymaps, e.g.

#+begin_src emacs-lisp
  ;; Rather than using `with-eval-after-load', using `eval-after-load' and giving
  ;; an explicit function name prevents duplicate addition of entries for the same
  ;; project.

  (eval-after-load 'project-hercules
    (defun define-my-config-map ()
      (let ((map (project-hercules-make-map "~/config/"
                                            :transient t)))
        ;; Add your keybindings...
        (define-key map (kbd "c") #'my-nixos-rebuild-build)
        (define-key map (kbd "R") #'my-nixos-rebuild-switch))))
#+end_src

Then you can dispatch the keymap for the project using =project-hercules-dispatch=.

If you don't define a map for the project, the default map is created according to =project-hercules-composed-maps=.
You can delete the map for the current project by running =project-hercules-remove-project= command, which should be run after you update =project-hercules-composed-maps= variable.
